### ISSUE TITLE
What the fuck is this hot garbage

### ISSUE THREAD

**Issue by Baxi-codes** [RavikumarRamesh/OVLC#1]
what is this cancer you made me run on my computer? Can you imagine installing burpsuite and it adding its logo on your terminal? Atleast  burpsuite logo would look better than whatever this ugly ass hacker bs going on here. 

![image](https://github.com/RavikumarRamesh/OVLC/assets/46259792/ff153e3e-3bbf-4361-823e-1261e24a490b)

Atleast provide a fucking uninstall script to remove this garbage from my daily driver. Ruined my day, thanks!

**Comment by Baxi-codes** [comment]
Stripping out the frustration:

Dear Ravi,

I hope this message finds you well. I am reaching out to address some significant concerns I have regarding the implementation and user experience of our project. After thorough examination and consideration, I believe it's essential to address these issues promptly to ensure the project's success and maintain user satisfaction.

1. **Forced Installation of External Dependencies:**
   - The project imposes the installation of external dependencies without prior consent or clear explanation. Users may not be comfortable with automatically downloading and executing scripts from external sources, especially without detailed information about their purpose and potential risks.

2. **Inadequate Documentation:**
   - The project lacks comprehensive documentation explaining its functionalities, dependencies, and potential implications. Users are left to navigate complex scripts without proper guidance, leading to confusion and potential security risks.

3. **Intrusive System Modifications:**
   - The project makes intrusive modifications to system configurations, such as changing the hostname and altering system files like `/etc/motd`. These modifications are performed without explicit user consent and may disrupt existing configurations or workflows.

4. **Lack of User Control:**
   - Users are not provided with sufficient control over the project's behavior. Critical actions such as system reboots are executed without user confirmation, potentially causing disruptions and data loss.

5. **Incompatibility and Stability Issues:**
   - The project's aggressive modifications and dependencies may introduce compatibility issues with existing software configurations and lead to system instability. Users may experience unexpected behavior or system crashes, undermining trust in the project's reliability.

In light of these concerns, I strongly recommend reassessing the project's approach and prioritizing user safety, transparency, and control. By addressing these issues and adopting best practices in software development and deployment, we can enhance the project's usability, security, and overall value to our users.

I welcome the opportunity to discuss these concerns further and collaborate on finding solutions that prioritize user satisfaction and mitigate risks effectively.

Thank you for your attention to this matter.

Sincerely,
Dhairya Baxi

**Comment by RavikumarRamesh** [comment]
Dear @Baxi-codes 

We strongly suggest that this project involves system configuration changes and the installation of multiple utilities such as dialog, Docker, etc. Additionally, it requires downloading multiple vulnerable labs. So, installing it on your primary working machine is not a good idea. Instead, I suggest creating a separate virtual machine based on Ubuntu LTS and installing it there. Installing it on your working machine, such as Kali Linux, may result in system breakage and potential availability issues.
